### ISSUE TITLE
an unexpected keyword argument 'rnn_type'

### ISSUE THREAD

**Issue by lulei0926** [Jester6136/pubmedBERT-BiLSTM-CRF#1]
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use BertModel for predictions without further training.
Traceback (most recent call last):
  File "train.py", line 87, in <module>
    student=config.create_student(nocrf=args.nocrf)
  File "/content/drive/MyDrive/BC/pubmedBERT-BiLSTM-CRF/flair/config_parser.py", line 235, in create_student
    return self.create_model(self.config,pretrained=self.load_pretrained(self.config), is_student=True)
  File "/content/drive/MyDrive/BC/pubmedBERT-BiLSTM-CRF/flair/config_parser.py", line 202, in create_model
    tagger = getattr(models,classname)(**kwargs, config=config)
TypeError: __init__() got an unexpected keyword argument 'rnn_type'

can you help me？

**Comment by Jester6136** [comment]
@lulei0926 Could you provide me with more information about the config_file?

**Comment by lulei0926** [comment]
The command i am using is: "CUDA_VISIBLE_DEVICES=0 python train.py --config config/pubmed_bilstm_crf.yaml". Except for using a local dataset, i haven't modified the content in the "config" file.
I'm not sure why it's throwing such an error.

**Comment by Jester6136** [comment]
@lulei0926  Sorry for the delayed response. You should remove rnn_type: LSTM.
